#!/bin/python
import onnx
import sys

def find_by_name(_list, name):
    for item in _list:
        if item.name == name:
            return item
    return None


model = onnx.load(sys.argv[1])
output = ""
for vi in model.graph.input:
    shape_string = ""
    for dim in vi.type.tensor_type.shape.dim:
        shape_string += f'{dim.dim_value},'
    print(f'{vi.name}[{shape_string.rstrip(",")}]')
